name: sample

services:
  tf:
    image: hashicorp/terraform:1.9.5
    environment:
      - AWS_ACCESS_KEY_ID=${YOUR_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${YOUR_AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./terraform:/terraform
    entrypoint: ash
    working_dir: /terraform
    tty: true
